# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!


target 'ContactApp' do
    pod ‘RealmSwift‘
    pod ‘Alamofire’, ‘~> 4.0’
    pod 'ImagePicker'
    pod 'DatePickerDialog'

end


